### ISSUE TITLE
Change project directory structure

### ISSUE THREAD

**Issue by mayankshah1607** [sarthakpranesh/ISOC-2019#1]
Current structure is not the best for designing REST APIs. Follow an MVC like architecture.
* Declare app.js in your root directory. Use it only to call middleware functions and mongo connection.
* Initialize mongodb connection only once, in app.js. No need to initialize connection for every model.
* No need for 'src' folder
* Create a 'models' folder and store all your models/schemas there.
* Create a routes folder and export these so that it can be used as a middleware in app.js
* Never write functions inside a route. Create a 'controllers' folder and write the functions there. Export these so that it can be used inside the routes.

You can use this project as a reference - https://github.com/yashvardhan-kukreja/quillhash-backend-task

**Comment by sarthakpranesh** [comment]
All changes done. Just having a slight doubt in the last point.
Can I have callbacks defined in routes.

**Comment by mayankshah1607** [comment]
Good work on changing the project directory.

To answer your question, routes need callback functions, that is (req,res) => {}
```
app.post('/route,(req, res) => { //The second arguement to the function is a callback
 // Logic
})
```

Is that what you mean?

**Comment by sarthakpranesh** [comment]
Not exactly...
What I am hoping to do is perform some action if the user is created or display a useful message if there was an error in the sign up. For eg:- If the user is created then use some api service for sending validation to the email, can I do this in the callback itself or should i prefer to make another file for the purpose export it to the controller for sign up and call it there when everything goes well.

**Comment by sarthakpranesh** [comment]
Decided to have a separate controller for sendgrid api service.
Mail service now working.

**Comment by mayankshah1607** [comment]
Have a separate route and a controller for email. You'll need 2 routes in the email - one for sending, and another for verification. Both of these need 2 separate controllers.
